#!/usr/bin/env python3
"""
Live AI Generation for Calidad Total Combinations using Groq API

Generates actual AI analyses using the Groq API for:
1. Calidad Total + Google Trends (single-source)
2. Calidad Total + All 5 sources (multi-source)
3. Calidad Total + Google Books, Bain Satisfaction (multi-source)

This will make actual API calls to Groq and generate fresh AI content.
"""

import asyncio
import os
import time
import logging
from typing import Dict, List, Any
from pathlib import Path

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Add project root to path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

# Import required modules
from database_implementation.precomputed_findings_db import get_precomputed_db_manager
from dashboard_app.key_findings.key_findings_service import get_key_findings_service

# Set up Groq API key
os.environ['GROQ_API_KEY'] = 'GROQ_API_KEY_PLACEHOLDER'

class CalidadTotalLiveAIGenerator:
    """Generator for live AI analyses using Groq API."""
    
    def __init__(self):
        """Initialize the generator with required services."""
        self.db_manager = get_precomputed_db_manager()
        self.key_findings_service = get_key_findings_service()
        
        # All available sources
        self.all_sources = [
            "Google Trends",
            "Google Books", 
            "Bain Usability",
            "Bain Satisfaction",
            "Crossref"
        ]
    
    async def generate_live_ai_analysis(self, tool_name: str, sources: List[str], language: str) -> Dict[str, Any]:
        """Generate live AI analysis using Groq API."""
        logger.info(f"🚀 Generating LIVE AI analysis: {tool_name} + {len(sources)} sources ({language})")
        logger.info(f"🎯 This will make ACTUAL API calls to Groq!")
        
        try:
            # Generate analysis using the actual AI service
            start_time = time.time()
            
            result = await self.key_findings_service.generate_key_findings(
                tool_name=tool_name,
                selected_sources=sources,
                language=language,
                force_refresh=True  # Force fresh AI generation
            )
            
            generation_time = time.time() - start_time
            
            if result["success"]:
                logger.info(f"✅ Live AI generation successful in {generation_time:.2f}s")
                logger.info(f"✅ This content was generated by actual AI, not templates!")
                
                # Log the actual AI generation
                data = result.get("data", {})
                logger.info(f"📊 Generated content summary:")
                logger.info(f"   Executive Summary: {len(data.get('executive_summary', ''))} chars")
                logger.info(f"   Principal Findings: {len(data.get('principal_findings', ''))} chars")
                logger.info(f"   Total sections: {len([k for k in data.keys() if data.get(k) and isinstance(data.get(k), str) and len(str(data.get(k))) \u003e 10])}")
                
                return result
            else:
                logger.error(f"❌ Live AI generation failed: {result.get('error', 'Unknown error')}")
                return result
                
        except Exception as e:
            logger.error(f"❌ Error in live AI generation: {e}")
            import traceback
            traceback.print_exc()
            return {
                "success": False,
                "error": f"Live AI generation failed: {str(e)}"
            }
    
    def store_live_ai_analysis(self, result: Dict[str, Any], tool_name: str, sources: List[str], language: str) -> bool:
        """Store the live AI-generated analysis in the database."""
        try:
            if not result["success"]:
                logger.warning(f"⚠️ Skipping storage due to generation failure")
                return False
            
            logger.info(f"🗄️ Storing LIVE AI-generated analysis in database")
            
            # Extract the AI-generated data
            analysis_data = result.get("data", {})
            
            # Generate combination hash
            combination_hash = self.db_manager.generate_combination_hash(
                tool_name=tool_name,
                selected_sources=sources,
                language=language
            )
            
            # Store the live AI-generated content
            storage_result = self.db_manager.store_precomputed_analysis(
                combination_hash=combination_hash,
                tool_name=tool_name,
                selected_sources=sources,
                language=language,
                analysis_data=analysis_data
            )
            
            if storage_result:
                logger.info(f"✅ Successfully stored LIVE AI-generated analysis!")
                return True
            else:
                logger.error(f"❌ Failed to store LIVE AI-generated analysis")
                return False
                
        except Exception as e:
            logger.error(f"❌ Error storing live AI analysis: {e}")
            return False
    
    async def generate_all_combinations(self):
        """Generate live AI analyses for all requested combinations."""
        logger.info("🚀 Starting LIVE AI generation for all Calidad Total combinations")
        logger.info("="*70)
        logger.info("🎯 This will make ACTUAL API calls to Groq and generate real AI content!")
        logger.info("="*70)
        
        combinations = [
            {
                "tool": "Calidad Total",
                "sources": ["Google Trends"],
                "language": "es",
                "description": "Single-source with Google Trends"
            },
            {
                "tool": "Calidad Total",
                "sources": ["Google Trends", "Google Books", "Bain Usability", "Bain Satisfaction", "Crossref"],
                "language": "es",
                "description": "Multi-source with all 5 sources"
            },
            {
                "tool": "Calidad Total",
                "sources": ["Google Books", "Bain Satisfaction"],
                "language": "es",
                "description": "Multi-source with Google Books and Bain Satisfaction"
            }
        ]
        
        results = []
        
        for i, combo in enumerate(combinations, 1):
            logger.info(f"\\n{'='*60}")
            logger.info(f"Processing combination {i}/{len(combinations)}: {combo['tool']} + {combo['description']}")
            logger.info(f"{'='*60}")
            
            start_time = time.time()
            
            # Generate live AI analysis
            result = await self.generate_live_ai_analysis(
                tool_name=combo["tool"],
                sources=combo["sources"],
                language=combo["language"]
            )
            
            generation_time = time.time() - start_time
            
            if result["success"]:
                logger.info(f"✅ Live AI generation successful in {generation_time:.2f}s")
                
                # Store the live AI-generated content
                storage_result = self.store_live_ai_analysis(
                    result=result,
                    tool_name=combo["tool"],
                    sources=combo["sources"],
                    language=combo["language"]
                )
                
                results.append({
                    "combination": combo,
                    "success": True,
                    "generation_time": generation_time,
                    "storage_success": storage_result,
                    "data": result.get("data", {})
                })
            else:
                logger.error(f"❌ Live AI generation failed: {result.get('error', 'Unknown error')}")
                results.append({
                    "combination": combo,
                    "success": False,
                    "generation_time": generation_time,
                    "error": result.get("error", "Unknown error")
                })
        
        return results
    
    def print_summary(self, results: List[Dict[str, Any]]):
        """Print a summary of the live AI generation results."""
        print("\n" + "="*70)
        print("📊 LIVE AI GENERATION SUMMARY")
        print("="*70)
        
        successful = sum(1 for r in results if r["success"])
        total = len(results)
        
        print(f"Total combinations processed: {total}")
        print(f"Successful generations: {successful}")
        print(f"Success rate: {successful/total*100:.1f}%")
        
        for i, result in enumerate(results, 1):
            combo = result["combination"]
            status = "✅ SUCCESS" if result["success"] else "❌ FAILED"
            
            print(f"\n{i}. {combo['tool']} + {combo['description']} - {status}")
            
            if result["success"]:
                print(f"   Generation time: {result['generation_time']:.2f}s")
                print(f"   Storage success: {'✅' if result['storage_success'] else '❌'}")
                
                # Show content summary
                data = result.get("data", {})
                sections = ['executive_summary', 'principal_findings', 'temporal_analysis', 'seasonal_analysis', 'fourier_analysis', 'strategic_synthesis', 'conclusions']
                present_sections = sum(1 for section in sections if data.get(section) and len(str(data.get(section, "")).strip()) \u003e 10)
                print(f"   Present sections: {present_sections}/{len(sections)}")
                print(f"   Confidence score: {data.get('confidence_score', 0):.2f}")
                print(f"   Data points: {data.get('data_points_analyzed', 0)}")
                
                # Show this was real AI content
                print(f"   🎯 This content was generated by ACTUAL AI, not templates!")
            else:
                print(f"   Error: {result.get('error', 'Unknown error')}")
        
        print(f"\n🎯 Overall Status: {'✅ ALL LIVE AI GENERATIONS SUCCESSFUL' if successful == total else '⚠️ SOME LIVE AI GENERATIONS FAILED'}")

if __name__ == "__main__":
    asyncio.run(main())